
CREATE TABLE WORKS_ON(
	EMPNO INT,
    PROJNO INT,
    HOURS_ALLOTTED DECIMAL(5,2),
    
    CONSTRAINT PK_WORKS_ON
		PRIMARY KEY(EMPNO,PROJNO),
	CONSTRAINT FK_WORKS_ON_EMP
		FOREIGN KEY(EMPNO) REFERENCES EMPLOYEE(EMPNO),
	CONSTRAINT FK_WORKS_ON_PROJ
		FOREIGN KEY(PROJNO) REFERENCES PROJECT(PROJNO)
);