-- CREATE TABLE TEMP_ID(
-- 	ID INT
-- );

-- INSERT INTO TEMP_ID VALUES(6);
-- INSERT INTO TEMP_ID VALUES(7);

-- SELECT * FROM TEMP_ID
-- TRUNCATE TABLE TEMP_ID;

-- SELECT * FROM TEMP_ID

DROP TABLE TEMP_ID;