INSERT INTO DEPARTMENT(DEPTNO,DNAME,LOC) VALUES (10,"ACCOUNTS","TRICHY");
INSERT INTO DEPARTMENT(DEPTNO,DNAME,LOC) VALUES (20,"IT","CHENNAI");
INSERT INTO DEPARTMENT(DEPTNO,DNAME,LOC) VALUES (30,"HR","MADURAI");
INSERT INTO DEPARTMENT(DEPTNO,DNAME,LOC) VALUES (40,"SALES","COIMBATORE");
INSERT INTO DEPARTMENT(DEPTNO,DNAME,LOC) VALUES (50,"R&D","BANGLORE");