CREATE TABLE EMPLOYEE(
	EMPNO INT PRIMARY KEY,
	ENAME VARCHAR(25) NOT NULL,
	JOB VARCHAR(15),
	MGR INT,
	HIREDATE DATE DEFAULT(CURRENT_DATE),
	SALARY DECIMAL(10,2),
	COMM DECIMAL(9,2),
	DEPTNO INT,
    
    FOREIGN KEY(MGR) REFERENCES EMPLOYEE(EMPNO),
    FOREIGN KEY(DEPTNO) REFERENCES DEPARTMENT(DEPTNO),
    CHECK (SALARY > 0)
);
