CREATE TABLE PROJECT(
	PROJNO INT PRIMARY KEY,
    PROJNAME VARCHAR(30) NOT NULL UNIQUE,
    BUDGET DECIMAL(12,2),
    STARTDATE DATE,
    DEPTNO INT,
    
    CHECK (BUDGET > 0),
    CONSTRAINT FK_DEPT_PROJ
		FOREIGN KEY(DEPTNO) REFERENCES DEPARTMENT(DEPTNO)
        
);
    