SELECT P.PROJNAME,W.EMPNO
FROM WORKS_ON W RIGHT OUTER JOIN 
PROJECT P ON P.PROJNO = W.PROJNO;

SELECT P.PROJNAME,W.EMPNO,W.HOURS_ALLOTTED
FROM PROJECT P LEFT OUTER JOIN WORKS_ON W 
ON P.PROJNO = W.PROJNO;